plugins:
- jekyll-remote-theme
remote_theme: zivong/ockham

title: Data Structures
tagline: Ideas about types of data structures
description: Thoughts about data structures. Made by <a href="https://twitter.com/John_Ryland">@John_Ryland</a>.
author:
  name: John Ryland
  url: https://twitter.com/John_Ryland

plugins:
  - jekyll-paginate
