@startuml
top to bottom direction
!theme cerulean-outline
(E) ..> (C): 1
(C) ..> (A): 2
(A) --> (A): 3
(A) --> (C): 4
(C) --> (C): 5
(C) ..> (B): 6
(B) --> (B): 7
(B) --> (C): 8
(C) --> (E): 9
(E) ..> (D): 10
(D) --> (D): 11
(D) --> (E): 12
(E) --> (E): 13
@enduml
