@startuml

top to bottom direction

skinparam ArrowColor DeepSkyBlue
skinparam rectangleBackgroundColor DeepSkyBlue
skinparam rectangleBorderColor DeepSkyBlue

rectangle A
rectangle B
rectangle C
rectangle D
rectangle E
rectangle F

A -d> B
B -d> C
B -d-> F
C -d-> D
C -d-> E

@enduml
