@startuml

top to bottom direction

skinparam ArrowColor DeepSkyBlue
skinparam rectangleBackgroundColor DeepSkyBlue
skinparam rectangleBorderColor DeepSkyBlue

rectangle Window
rectangle HBox
rectangle VBox
rectangle Child1
rectangle Child2
rectangle Child3

Window -d-> HBox
HBox -d-> VBox
HBox -d-> Child3
VBox -d-> Child1
VBox -d-> Child2

@enduml
