@startuml
top to bottom direction
!theme cerulean-outline
(A) --> (A): 1
(A) --> (B): 2
(B) --> (B): 3
(B) --> (C): 4
(C) --> (C): 5
(C) ..> (B): 6
(B) --> (D): 7
(D) --> (D): 8
(D) ..> (B): 9
(B) ..> (A): 10
(A) --> (E): 11
(E) --> (E): 12
(E) ..> (A): 13
@enduml
