@startuml
scale 0.5
!theme cerulean-outline
object A {
  nextSibling
  firstChild
}
object B {
  nextSibling
  firstChild
}
object C {
  nextSibling
  firstChild
}
object D {
  nextSibling
  firstChild
}
object E {
  nextSibling
  firstChild
}
A::firstChild --> B
B::firstChild --> C
B::nextSibling -r-> E
C::nextSibling -r-> D
@enduml
