@startuml
scale 0.5
!theme cerulean-outline
object Item1 {
  value
  next
}
object Item2 {
  value
  next
}
object Item3 {
  value
  next
}
object NULL

Item1::next --> Item2
Item2::next --> Item3
Item3::next --> NULL
@enduml
